name: Deploy to Nginx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with: 
          clean: false
      - name: Npm Install
        run: npm install
      - name: Npm Run Build
        run: npm run build
      - name: Start Nginx
        run: docker restart nginx
      - name: Upload Nginx Server Config
        run: docker cp nginx-strix.conf nginx:/etc/nginx/conf.d/default.conf
      - name: Delete Old Dist Files
        run: docker exec -i nginx bash -c "rm -rf /mnt/strixweb"
      - name: Copy Dist Files
        run: docker cp dist nginx:/mnt/strixweb
      - name: Execute CMD
        run: docker exec -i nginx bash -c "nginx -s reload"
