name: Build and Deploy to Docker

on:
  push:
    branches: ['master']

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Project
        run: pnpm run build

      - name: Remove Existing Docker Container
        run: |
          if docker ps -a | grep StrixNginx; then
            docker rm -f StrixNginx
          else
            echo "No Container"
          fi

      - name: Start Docker Container
        run: |
          if ! docker ps -a | grep StrixNginx; then
            docker run --restart=no -p 13232:13232 --name StrixNginx -v $PWD/nginx.conf:/etc/nginx/conf.d/app.conf -v $PWD/dist:/mnt/app -d nginx:stable
          fi

      - name: Reload Nginx Configuration
        run: docker exec -i StrixNginx bash -c "nginx -s reload"
